apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
      # Using ClusterIP to expose the application within the cluster
  type: ClusterIP
  selector:
    app: nginx-demo
  ports:
    - port: 80          # Service port exposed inside the cluster
      targetPort: 80    # Container port on the nginx pod
